<style>
    body { font-family: DejaVu Sans, sans-serif; font-size: 10px; }
    h1, h2 { margin: 0 0 6px 0; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 12px; }
    th, td { border: 1px solid #333; padding: 4px; vertical-align: top; }
    th { background: #f0f0f0; }
    .meta td { border: none; padding: 2px 4px; }
</style>

<table class="meta">
    <tr>
        <td><strong>Document</strong></td>
        <td>Asset & Activity Report</td>
        <td><strong>Generated At</strong></td>
        <td>{{ now()->format('Y-m-d H:i:s') }}</td>
    </tr>
    <tr>
        <td><strong>Generated By</strong></td>
        <td>{{ auth()->user()->name }} ({{ auth()->user()->role }})</td>
        <td><strong>System</strong></td>
        <td>Inventory Asset Management</td>
    </tr>
</table>
